[project]
name = "oligos_prediction"
version = "0.1.0"
dependencies = [
    "numpy",
    "bio",
    "notebook",
    "ViennaRNA",
    "pandas",
    "scikit-learn==1.5.2",
    "xgboost==2.1.2",
    "dill",
]

[tool.setuptools.package-data]
"oligos_prediction" = ["artifacts/saved_models/*"]